insert into public."Class" (class_id, timeslot_id, class_name, description) values (1, 16, 'Crossfit', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (2, 5, 'Bootcamp', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (3, 1, 'Barre', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (4, 19, 'Spinning', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (5, 10, 'Zumba', 'Zumba Latin music with dance moves');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (6, 6, 'Pilates', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (7, 20, 'Barre', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (8, 15, 'Barre', 'TRX -uses bodyweight exercises and straps');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (9, 7, 'Pilates', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (10, 5, 'Spinning', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (11, 13, 'Spinning', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (12, 8, 'Crossfit', 'Zumba Latin music with dance moves');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (13, 3, 'Bootcamp', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (14, 18, 'Zumba', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (15, 19, 'Crossfit', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (16, 8, 'Spinning', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (17, 8, 'Spinning', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (18, 18, 'Crossfit', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (19, 24, 'Bootcamp', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (20, 4, 'Yoga', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (21, 23, 'Yoga', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (22, 21, 'Kickboxing', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (23, 10, 'Barre', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (24, 22, 'Spinning', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (25, 7, 'TRX', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (26, 20, 'Yoga', 'TRX -uses bodyweight exercises and straps');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (27, 24, 'Pilates', 'TRX -uses bodyweight exercises and straps');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (28, 12, 'Barre', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (29, 18, 'Pilates', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (30, 3, 'Kickboxing', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (31, 17, 'HIIT', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (32, 23, 'Kickboxing', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (33, 16, 'Crossfit', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (34, 1, 'Barre', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (35, 18, 'Pilates', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (36, 20, 'Bootcamp', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (37, 20, 'Kickboxing', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (38, 6, 'TRX', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (39, 17, 'TRX', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (40, 15, 'HIIT', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (41, 12, 'Bootcamp', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (42, 11, 'Spinning', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (43, 15, 'Pilates', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (44, 5, 'Crossfit', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (45, 14, 'Zumba', 'Zumba Latin music with dance moves');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (46, 9, 'Spinning', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (47, 9, 'Crossfit', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (48, 18, 'Barre', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (49, 19, 'Bootcamp', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (50, 18, 'Zumba', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (51, 9, 'TRX', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (52, 7, 'Bootcamp', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (53, 6, 'Pilates', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (54, 9, 'Crossfit', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (55, 22, 'Pilates', 'TRX -uses bodyweight exercises and straps');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (56, 15, 'HIIT', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (57, 1, 'Yoga', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (58, 2, 'Pilates', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (59, 13, 'TRX', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (60, 12, 'Kickboxing', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (61, 22, 'TRX', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (62, 16, 'TRX', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (63, 18, 'Spinning', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (64, 24, 'Zumba', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (65, 24, 'Yoga', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (66, 9, 'Spinning', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (67, 23, 'TRX', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (68, 14, 'Crossfit', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (69, 19, 'Zumba', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (70, 16, 'Kickboxing', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (71, 2, 'Zumba', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (72, 18, 'Spinning', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (73, 4, 'Spinning', 'Boxing-inspired class');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (74, 9, 'Zumba', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (75, 10, 'Zumba', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (76, 22, 'TRX', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (77, 16, 'Pilates', 'HIIT -cardio and strength exercies');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (78, 5, 'Barre', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (79, 7, 'Barre', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (80, 7, 'Barre', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (81, 8, 'Kickboxing', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (82, 9, 'Zumba', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (83, 17, 'Pilates', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (84, 18, 'Barre', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (85, 3, 'Zumba', 'Indoor cycling -simulates outdoor riding');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (86, 12, 'Bootcamp', 'Yoga -flexibility and relaxation');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (87, 19, 'Pilates', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (88, 15, 'Pilates', 'Aqua aerobics -low-impact cardio and resistance training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (89, 7, 'Bootcamp', 'Bootcamp-style bodyweight exercises');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (90, 17, 'Bootcamp', 'TRX -uses bodyweight exercises and straps');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (91, 7, 'Bootcamp', 'Barre -ballet-inspired moves with strength training');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (92, 3, 'HIIT', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (93, 21, 'Crossfit', 'Zumba Latin music with dance moves');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (94, 10, 'Barre', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (95, 21, 'HIIT', 'Pilates -core strength and stability');
insert into public."Class" (class_id, timeslot_id, class_name, description) values (96, 19, 'Bootcamp', 'Boxing-inspired class');
