insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (1, 10, 'Spin', 'Boxing class - punching and kicking drills', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (2, 110, 'Kickboxing', 'Barre - ballet-inspired moves and strength training', 21);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (3, 7, 'Spin', 'Barre - ballet-inspired moves and strength training', 26);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (4, 108, 'HIIT', 'Bootcamp - a variety of exercises to improve overall fitness', 17);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (5, 78, 'TRX', 'Cycling class that simulates outdoor riding', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (6, 13, 'Kickboxing', 'TRX class - build strength and stability', 32);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (7, 56, 'Zumba', 'Bootcamp - a variety of exercises to improve overall fitness', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (8, 35, 'Barre', 'Zumba - dance and aerobic exercises', 16);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (9, 28, 'TRX', 'Aqua aerobics - low-impact', 31);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (10, 67, 'Bootcamp', 'Boxing class - punching and kicking drills', 13);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (11, 40, 'Bootcamp', 'Barre - ballet-inspired moves and strength training', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (12, 75, 'TRX', 'Barre - ballet-inspired moves and strength training', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (13, 93, 'Kickboxing', 'Boxing class - punching and kicking drills', 2);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (14, 77, 'Kickboxing', 'Zumba - dance and aerobic exercises', 31);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (15, 51, 'HIIT', 'Barre - ballet-inspired moves and strength training', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (16, 25, 'Spin', 'High-intensity interval training (HIIT) - cardio and strength exercises', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (17, 93, 'Barre', 'Cycling class that simulates outdoor riding', 34);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (18, 13, 'Spin', 'Aqua aerobics - low-impact', 8);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (19, 60, 'Crossfit', 'TRX class - build strength and stability', 35);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (20, 38, 'Zumba', 'Zumba - dance and aerobic exercises', 10);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (21, 70, 'Bootcamp', 'Cycling class that simulates outdoor riding', 21);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (22, 73, 'Barre', 'High-intensity interval training (HIIT) - cardio and strength exercises', 37);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (23, 17, 'HIIT', 'Barre - ballet-inspired moves and strength training', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (24, 14, 'Kickboxing', 'Boxing class - punching and kicking drills', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (25, 39, 'Zumba', 'Barre - ballet-inspired moves and strength training', 29);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (26, 37, 'Kickboxing', 'TRX class - build strength and stability', 11);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (27, 6, 'Barre', 'Boxing class - punching and kicking drills', 30);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (28, 42, 'TRX', 'Aqua aerobics - low-impact', 34);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (29, 85, 'TRX', 'Pilates - strengthens core muscles', 37);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (30, 41, 'TRX', 'Bootcamp - a variety of exercises to improve overall fitness', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (31, 69, 'TRX', 'Zumba - dance and aerobic exercises', 49);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (32, 29, 'Zumba', 'Zumba - dance and aerobic exercises', 15);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (33, 30, 'Kickboxing', 'Bootcamp - a variety of exercises to improve overall fitness', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (34, 77, 'Zumba', 'Barre - ballet-inspired moves and strength training', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (35, 32, 'HIIT', 'Aqua aerobics - low-impact', 37);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (36, 95, 'Yoga', 'Boxing class - punching and kicking drills', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (37, 9, 'Crossfit', 'TRX class - build strength and stability', 28);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (38, 102, 'Bootcamp', 'Barre - ballet-inspired moves and strength training', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (39, 52, 'Barre', 'Bootcamp - a variety of exercises to improve overall fitness', 29);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (40, 28, 'HIIT', 'Cycling class that simulates outdoor riding', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (41, 51, 'Spin', 'Boxing class - punching and kicking drills', 45);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (42, 69, 'Spin', 'Yoga - flexibility and relaxation', 7);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (43, 115, 'TRX', 'TRX class - build strength and stability', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (44, 71, 'Barre', 'Barre - ballet-inspired moves and strength training', 22);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (45, 88, 'HIIT', 'High-intensity interval training (HIIT) - cardio and strength exercises', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (46, 76, 'Zumba', 'Boxing class - punching and kicking drills', 43);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (47, 11, 'Crossfit', 'Bootcamp - a variety of exercises to improve overall fitness', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (48, 34, 'Bootcamp', 'Boxing class - punching and kicking drills', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (49, 119, 'Yoga', 'Bootcamp - a variety of exercises to improve overall fitness', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (50, 108, 'Pilates', 'Yoga - flexibility and relaxation', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (51, 104, 'Kickboxing', 'TRX class - build strength and stability', 6);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (52, 30, 'Spin', 'Zumba - dance and aerobic exercises', 45);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (53, 110, 'Yoga', 'Aqua aerobics - low-impact', 24);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (54, 25, 'Kickboxing', 'Boxing class - punching and kicking drills', 31);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (55, 120, 'Yoga', 'Barre - ballet-inspired moves and strength training', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (56, 33, 'Barre', 'Barre - ballet-inspired moves and strength training', 9);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (57, 75, 'Yoga', 'Aqua aerobics - low-impact', 9);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (58, 48, 'Barre', 'TRX class - build strength and stability', 48);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (59, 25, 'Yoga', 'Aqua aerobics - low-impact', 28);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (60, 65, 'Bootcamp', 'Yoga - flexibility and relaxation', 23);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (61, 69, 'Kickboxing', 'Bootcamp - a variety of exercises to improve overall fitness', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (62, 73, 'Spin', 'Aqua aerobics - low-impact', 28);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (63, 108, 'Kickboxing', 'Cycling class that simulates outdoor riding', 32);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (64, 72, 'HIIT', 'Barre - ballet-inspired moves and strength training', 14);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (65, 96, 'Spin', 'Yoga - flexibility and relaxation', 2);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (66, 19, 'Pilates', 'Cycling class that simulates outdoor riding', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (67, 14, 'Spin', 'Pilates - strengthens core muscles', 15);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (68, 118, 'Yoga', 'TRX class - build strength and stability', 45);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (69, 49, 'Yoga', 'Pilates - strengthens core muscles', 32);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (70, 62, 'Spin', 'High-intensity interval training (HIIT) - cardio and strength exercises', 45);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (71, 36, 'Kickboxing', 'Bootcamp - a variety of exercises to improve overall fitness', 7);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (72, 96, 'Crossfit', 'Bootcamp - a variety of exercises to improve overall fitness', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (73, 17, 'Crossfit', 'Cycling class that simulates outdoor riding', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (74, 92, 'Barre', 'Yoga - flexibility and relaxation', 39);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (75, 69, 'Zumba', 'Zumba - dance and aerobic exercises', 37);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (76, 19, 'Bootcamp', 'Bootcamp - a variety of exercises to improve overall fitness', 9);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (77, 85, 'Barre', 'Cycling class that simulates outdoor riding', 17);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (78, 49, 'Barre', 'Yoga - flexibility and relaxation', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (79, 52, 'Yoga', 'High-intensity interval training (HIIT) - cardio and strength exercises', 23);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (80, 78, 'Yoga', 'Boxing class - punching and kicking drills', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (81, 111, 'Bootcamp', 'Aqua aerobics - low-impact', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (82, 86, 'Yoga', 'TRX class - build strength and stability', 33);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (83, 101, 'Spin', 'High-intensity interval training (HIIT) - cardio and strength exercises', 27);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (84, 4, 'Kickboxing', 'Aqua aerobics - low-impact', 12);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (85, 20, 'Barre', 'Zumba - dance and aerobic exercises', 30);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (86, 59, 'Yoga', 'Pilates - strengthens core muscles', 10);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (87, 67, 'TRX', 'Yoga - flexibility and relaxation', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (88, 24, 'Pilates', 'Yoga - flexibility and relaxation', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (89, 98, 'Bootcamp', 'Bootcamp - a variety of exercises to improve overall fitness', 18);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (90, 92, 'Yoga', 'Pilates - strengthens core muscles', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (91, 32, 'TRX', 'Yoga - flexibility and relaxation', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (92, 12, 'HIIT', 'Aqua aerobics - low-impact', 0);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (93, 11, 'Spin', 'High-intensity interval training (HIIT) - cardio and strength exercises', 7);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (94, 7, 'Spin', 'Barre - ballet-inspired moves and strength training', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (95, 22, 'Yoga', 'Cycling class that simulates outdoor riding', 13);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (96, 36, 'Crossfit', 'High-intensity interval training (HIIT) - cardio and strength exercises', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (97, 61, 'TRX', 'Zumba - dance and aerobic exercises', 49);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (98, 76, 'Spin', 'Boxing class - punching and kicking drills', 16);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (99, 42, 'Zumba', 'Barre - ballet-inspired moves and strength training', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (100, 15, 'Yoga', 'Yoga - flexibility and relaxation', 34);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (101, 69, 'Yoga', 'Yoga - flexibility and relaxation', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (102, 27, 'HIIT', 'Zumba - dance and aerobic exercises', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (103, 33, 'Barre', 'Aqua aerobics - low-impact', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (104, 93, 'Spin', 'Bootcamp - a variety of exercises to improve overall fitness', 7);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (105, 91, 'Yoga', 'High-intensity interval training (HIIT) - cardio and strength exercises', 10);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (106, 103, 'Pilates', 'Aqua aerobics - low-impact', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (107, 15, 'Bootcamp', 'Cycling class that simulates outdoor riding', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (108, 81, 'Yoga', 'Boxing class - punching and kicking drills', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (109, 2, 'HIIT', 'Bootcamp - a variety of exercises to improve overall fitness', 8);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (110, 102, 'Pilates', 'TRX class - build strength and stability', 30);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (111, 50, 'TRX', 'TRX class - build strength and stability', 44);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (112, 83, 'Bootcamp', 'Barre - ballet-inspired moves and strength training', 38);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (113, 81, 'HIIT', 'High-intensity interval training (HIIT) - cardio and strength exercises', 49);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (114, 17, 'HIIT', 'Yoga - flexibility and relaxation', 11);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (115, 50, 'Pilates', 'Boxing class - punching and kicking drills', 11);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (116, 59, 'Barre', 'Yoga - flexibility and relaxation', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (117, 113, 'TRX', 'High-intensity interval training (HIIT) - cardio and strength exercises', 18);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (118, 113, 'HIIT', 'TRX class - build strength and stability', 24);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (119, 44, 'Yoga', 'TRX class - build strength and stability', 15);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (120, 31, 'TRX', 'Barre - ballet-inspired moves and strength training', 20);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (121, 91, 'TRX', 'Boxing class - punching and kicking drills', 34);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (122, 77, 'Spin', 'Cycling class that simulates outdoor riding', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (123, 95, 'Kickboxing', 'Cycling class that simulates outdoor riding', 23);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (124, 23, 'Bootcamp', 'Pilates - strengthens core muscles', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (125, 19, 'Pilates', 'Boxing class - punching and kicking drills', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (126, 81, 'Crossfit', 'Barre - ballet-inspired moves and strength training', 38);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (127, 33, 'Yoga', 'Aqua aerobics - low-impact', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (128, 85, 'Yoga', 'Boxing class - punching and kicking drills', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (129, 94, 'Yoga', 'Aqua aerobics - low-impact', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (130, 50, 'Barre', 'Cycling class that simulates outdoor riding', 29);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (131, 31, 'Crossfit', 'Barre - ballet-inspired moves and strength training', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (132, 111, 'HIIT', 'Bootcamp - a variety of exercises to improve overall fitness', 45);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (133, 120, 'Crossfit', 'Pilates - strengthens core muscles', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (134, 12, 'TRX', 'Barre - ballet-inspired moves and strength training', 2);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (135, 100, 'Crossfit', 'High-intensity interval training (HIIT) - cardio and strength exercises', 43);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (136, 71, 'Kickboxing', 'Bootcamp - a variety of exercises to improve overall fitness', 27);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (137, 73, 'TRX', 'High-intensity interval training (HIIT) - cardio and strength exercises', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (138, 45, 'Barre', 'Cycling class that simulates outdoor riding', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (139, 41, 'Kickboxing', 'Yoga - flexibility and relaxation', 7);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (140, 55, 'Crossfit', 'Bootcamp - a variety of exercises to improve overall fitness', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (141, 115, 'TRX', 'Bootcamp - a variety of exercises to improve overall fitness', 2);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (142, 93, 'Crossfit', 'Boxing class - punching and kicking drills', 12);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (143, 51, 'TRX', 'Zumba - dance and aerobic exercises', 37);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (144, 70, 'Zumba', 'Zumba - dance and aerobic exercises', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (145, 48, 'Crossfit', 'Zumba - dance and aerobic exercises', 16);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (146, 31, 'Barre', 'Boxing class - punching and kicking drills', 22);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (147, 103, 'Pilates', 'Zumba - dance and aerobic exercises', 28);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (148, 34, 'TRX', 'Bootcamp - a variety of exercises to improve overall fitness', 15);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (149, 109, 'TRX', 'High-intensity interval training (HIIT) - cardio and strength exercises', 27);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (150, 92, 'Kickboxing', 'Boxing class - punching and kicking drills', 29);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (151, 97, 'Spin', 'Aqua aerobics - low-impact', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (152, 60, 'HIIT', 'Yoga - flexibility and relaxation', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (153, 41, 'Zumba', 'Boxing class - punching and kicking drills', 9);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (154, 1, 'Yoga', 'Pilates - strengthens core muscles', 10);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (155, 101, 'HIIT', 'Bootcamp - a variety of exercises to improve overall fitness', 8);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (156, 77, 'Spin', 'Boxing class - punching and kicking drills', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (157, 118, 'HIIT', 'Zumba - dance and aerobic exercises', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (158, 17, 'Pilates', 'Boxing class - punching and kicking drills', 11);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (159, 82, 'Bootcamp', 'Barre - ballet-inspired moves and strength training', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (160, 105, 'Barre', 'High-intensity interval training (HIIT) - cardio and strength exercises', 16);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (161, 17, 'Spin', 'High-intensity interval training (HIIT) - cardio and strength exercises', 4);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (162, 85, 'Pilates', 'Yoga - flexibility and relaxation', 21);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (163, 13, 'Zumba', 'Zumba - dance and aerobic exercises', 16);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (164, 16, 'Spin', 'Zumba - dance and aerobic exercises', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (165, 66, 'Crossfit', 'Zumba - dance and aerobic exercises', 39);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (166, 86, 'Zumba', 'Cycling class that simulates outdoor riding', 35);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (167, 113, 'Pilates', 'Yoga - flexibility and relaxation', 21);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (168, 69, 'Spin', 'Zumba - dance and aerobic exercises', 1);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (169, 35, 'Yoga', 'Cycling class that simulates outdoor riding', 22);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (170, 111, 'Bootcamp', 'High-intensity interval training (HIIT) - cardio and strength exercises', 26);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (171, 99, 'Crossfit', 'Aqua aerobics - low-impact', 20);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (172, 111, 'Crossfit', 'High-intensity interval training (HIIT) - cardio and strength exercises', 46);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (173, 2, 'Crossfit', 'Yoga - flexibility and relaxation', 21);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (174, 106, 'Yoga', 'Boxing class - punching and kicking drills', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (175, 33, 'Barre', 'Bootcamp - a variety of exercises to improve overall fitness', 23);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (176, 61, 'Zumba', 'Bootcamp - a variety of exercises to improve overall fitness', 50);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (177, 33, 'Kickboxing', 'Cycling class that simulates outdoor riding', 6);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (178, 25, 'Pilates', 'Bootcamp - a variety of exercises to improve overall fitness', 14);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (179, 44, 'Pilates', 'High-intensity interval training (HIIT) - cardio and strength exercises', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (180, 37, 'Barre', 'Cycling class that simulates outdoor riding', 3);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (181, 23, 'Zumba', 'Aqua aerobics - low-impact', 28);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (182, 56, 'Barre', 'Pilates - strengthens core muscles', 18);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (183, 46, 'HIIT', 'Yoga - flexibility and relaxation', 0);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (184, 26, 'Yoga', 'Bootcamp - a variety of exercises to improve overall fitness', 40);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (185, 16, 'Pilates', 'Barre - ballet-inspired moves and strength training', 48);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (186, 8, 'HIIT', 'Zumba - dance and aerobic exercises', 17);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (187, 95, 'TRX', 'Cycling class that simulates outdoor riding', 35);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (188, 51, 'Pilates', 'Bootcamp - a variety of exercises to improve overall fitness', 25);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (189, 52, 'Crossfit', 'High-intensity interval training (HIIT) - cardio and strength exercises', 13);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (190, 64, 'Pilates', 'High-intensity interval training (HIIT) - cardio and strength exercises', 36);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (191, 61, 'Barre', 'Cycling class that simulates outdoor riding', 19);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (192, 90, 'Bootcamp', 'Aqua aerobics - low-impact', 18);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (193, 18, 'Spin', 'Yoga - flexibility and relaxation', 41);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (194, 30, 'Spin', 'Boxing class - punching and kicking drills', 47);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (195, 47, 'Zumba', 'Boxing class - punching and kicking drills', 5);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (196, 80, 'Zumba', 'TRX class - build strength and stability', 18);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (197, 55, 'Kickboxing', 'Boxing class - punching and kicking drills', 30);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (198, 57, 'Zumba', 'Pilates - strengthens core muscles', 17);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (199, 40, 'Crossfit', 'Boxing class - punching and kicking drills', 42);
insert into public."Class" (class_id, timeslot_id, class_name, description, capacity) values (200, 64, 'Kickboxing', 'Barre - ballet-inspired moves and strength training', 12);
